server:
  port: 8081
  contextPath: /wireless

spring:
  freemarker:
    requestContextAttribute: request

multipart:
  maxFileSize: 20MB
  maxRequestSize: 20MB

exp-platform:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/exp_platform
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver

upload:
  file:
    path: /Users/xiazhiyang/Desktop/upload/

download:
  file:
    path: /Users/xiazhiyang/Desktop/upload/